server:
  port: 8083

spring:
  application:
    name: query-api
  datasource:
    url: ${PULSE_DB_URL:jdbc:cubrid://localhost:30000/observability:::}
    username: ${PULSE_DB_USER:dba}
    password: ${PULSE_DB_PASS:dba}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
      connection-timeout: 3000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

